spring:
  application:
    name: service-consumer
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12580/eureka

# 定义负载均衡的规则接口
# 格式是：`{服务名称}.ribbon.NFLoadBalancerRuleClassName`，值就是IRule的实现类。
#service-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms


